title: Data Story for the Project
description: Data Story for the Project
plugins:
  - jekyll-remote-theme
remote_theme: Sylhare/Type-on-Strap
post_navigation: false
header_text: Historical and Sociocultural Analysis of Film Genre Trends
