title: Historical and sociocultural analysis of film genre trends
description: Data Story for the project
show_downloads: true
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
plugins:
  - jekyll-remote-theme
remote_theme: Sylhare/Type-on-Strap
